# src/toolbridge/generate.py
"""Write a plain Python package for one tool: methods per control, per workflow, per opt-in direct call."""
from __future__ import annotations

import re
from pathlib import Path

from .project import Project

_HEADER = '''r"""API for {window}, generated by ToolBridge from {app}.

Regenerate with:  toolbridge generate --project "{project}"
"""
from pathlib import Path

from toolbridge.project import Project
from toolbridge.runtime import Result, Session
from toolbridge.workflow import run_workflow

PROJECT = Path(r"{project}")
CONTROLS = {controls!r}
WORKFLOWS = {workflows!r}


class Tool:
    """One running instance of {window}. Methods are thread-safe (one action at a time)."""

    def __init__(self, project_dir=PROJECT):
        self._project = Project(Path(project_dir))
        cfg = self._project.config
        self.session = Session(self._project.load_target(), cfg["deny"], self._project.runs_dir)
        self._workflows = self._project.workflows()
'''


def _ident(s: str) -> str:
    s = re.sub(r"\W+", "_", s).strip("_")
    return s if s and not s[0].isdigit() else f"c_{s}"


def generate(project: Project, package: str | None = None) -> Path:
    t, cfg = project.load_target(), project.config
    deny = set(cfg["deny"])
    workflows = project.workflows()
    package = package or _ident(t["window"]).lower() + "_api"
    lines = [_HEADER.format(window=t["window"], app=t["app"], project=project.root.resolve(),
                            controls=[c["id"] for c in t["controls"]], workflows=list(workflows))]
    for c in t["controls"]:
        cid, name = c["id"], _ident(c["id"])
        what = f'{c["type"]} "{c["label"]}"' if c["label"] else c["type"]
        if cid not in deny:
            if c["type"] in ("Button", "MenuItem", "CheckBox", "RadioButton", "TabItem", "ListItem"):
                lines.append(f'    def click_{name}(self):\n        """Click {what}."""\n'
                             f'        self.session.click({cid!r})\n')
            if c["type"] == "Edit":
                lines.append(f'    def set_{name}(self, value):\n        """Type into {what}."""\n'
                             f'        self.session.set_text({cid!r}, value)\n')
            if c["type"] == "ComboBox":
                lines.append(f'    def select_{name}(self, value):\n        """Pick an option in {what}."""\n'
                             f'        self.session.select({cid!r}, value)\n')
        lines.append(f'    def read_{name}(self) -> str:\n        """Current text of {what}."""\n'
                     f'        return self.session.read({cid!r})\n')
    for wname, wf in workflows.items():
        params = ", ".join(wf["params"])
        steps = "\n        ".join(
            "- " + " ".join(str(x) for x in (s["do"], s.get("target"), s.get("value", s.get("until"))) if x not in (None, ""))
            for s in wf["steps"])
        kwargs = ", ".join(f"{p}={p}" for p in wf["params"])
        lines.append(f'    def {_ident(wname)}(self{", " + params if params else ""}) -> Result:\n'
                     f'        """Recorded workflow. Steps:\n        {steps}\n        """\n'
                     f'        return run_workflow(self.session, self._workflows[{wname!r}]{", " + kwargs if kwargs else ""})\n')
    sigs = {s.split("(")[0]: s for s in t["dotnet"]["methods"]}
    assemblies = t["dotnet"].get("assemblies", [])
    for full in cfg["direct"]:
        asm = next((a for a in assemblies if Path(a).stem == full.split(".")[0]), assemblies[-1] if assemblies else "")
        lines.append(f'    def {_ident(full.rsplit(".", 1)[1])}_direct(self, *args):\n'
                     f'        """Direct .NET call, no GUI: {sigs.get(full, full)}"""\n'
                     f'        from toolbridge.direct import call\n'
                     f'        return call(Path(r"{asm}"), {full!r}, *args)\n')
    pkg = project.root / package
    pkg.mkdir(exist_ok=True)
    (pkg / "__init__.py").write_text("\n".join(lines), encoding="utf-8")
    return pkg
